#!/bin/sh
#
# PROVIDE: tubenews_daemon
# REQUIRE: NETWORKING
# KEYWORD: shutdown
#
# Add the following to /etc/rc.conf[.local] to enable this service:
#
# tubenews_daemon_enable="YES"

. /etc/rc.subr

name="tubenews_daemon"
rcvar=tubenews_daemon_enable
pidfile="/var/www/TubeNews/state/tubenews_daemon.pid"

: ${tubenews_daemon_enable:="NO"}
: ${tubenews_daemon_dir:="/var/www/TubeNews"}

command="/usr/sbin/daemon"
command_args="-P ${pidfile} /usr/local/bin/python3 ${tubenews_daemon_dir}/TubeNews.py"

load_rc_config $name
run_rc_command "$1"

